# Generated by Django 4.2.10 on 2024-03-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('descreption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glocose', models.FloatField(max_length=10)),
                ('bmi', models.FloatField(max_length=10)),
                ('prusser', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checkIn', models.DateTimeField(auto_now_add=True)),
                ('checkOut', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
